/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhofinal;

import trabalhofinal.Mapa.Tempo;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Henrique
 */
public class GUITempos extends javax.swing.JFrame {

    /**
     * Creates new form GUITempos
     */
    public GUITempos() {
        initComponents();
    }

    public void preencheTabela(Tempo t) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel(); 
        model.addRow(new Vector());
        jTable.setValueAt(t.getNome(), jTable.getRowCount()-1, 0);
        jTable.setValueAt(t.getDificuldade(), jTable.getRowCount()-1, 1);
        for (int i = 0; i < t.getTempos().size(); i++) {
            jTable.setValueAt(t.getTempos().get(i), jTable.getRowCount()-1, i+2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dificuldade", "Fase 1", "Fase 2", "Fase 3", "Fase 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(722, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
