/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.Chat;

import java.awt.Rectangle;
import javax.swing.SwingUtilities;

/**
 *
 * @author henrique
 */
public class GUIOpenMessage extends javax.swing.JFrame {

    /**
     * Creates new form OpenMessage
     *
     * @param message
     */
    public GUIOpenMessage(String message) {
        initComponents();
        jTextAreaMessage.setText(message);
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                jTextAreaMessage.scrollRectToVisible(new Rectangle(1, 1, 10, 10));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextAreaMessage.setEditable(false);
        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setLineWrap(true);
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaMessage);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(649, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMessage;
    // End of variables declaration//GEN-END:variables
}
